results_directory='results'

threads.number_add=4
execution.repeat=5
plot.length=16
plot.width=8

vertices.min_number=10
vertices.max_number=5000
vertices.number_step=250

edges.sparse.min_offset=0.25
edges.sparse.max_offset=0.3
edges.medium.min_offset=0.05
edges.medium.max_offset=0.2
edges.dense.min_offset=0.05
edges.dense.max_offset=0.2
edges.rewiring_prob=0.3
edges.min_weight=1
edges.max_weight=100000000

kruskal.filter.threshold_part=0.005
